# -*- coding: utf-8 -*-
"""Dorah_Search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXyI_dSKLZZn7Wzf1KsdKYf4jp7-v4vo

# Wikipédia API
"""

!pip3 install wikipedia-api

import wikipediaapi

wiki_wiki = wikipediaapi.Wikipedia('Dorah (https://github.com/faduzin/ProjetoDorah)', 'pt')

page_py = wiki_wiki.page('Produtos Notáveis')

print(page_py.exists())

print(page_py.summary)

"""# Google API

"""

!pip3 install google-api-python-client

from googleapiclient.discovery import build

my_api_key = 'AIzaSyA22aAixSFOwUjeuPcmrkfTTBIbOkh5-t0'
my_cse_id = '87aec49bd378c41f9'

def google_search(search_term, api_key, cse_id, **kwargs):
    service = build("customsearch", "v1", developerKey=api_key)
    res = service.cse().list(q=search_term, cx=cse_id, **kwargs).execute()

    return res

result = google_search('Produtos Notáveis', my_api_key, my_cse_id)

print(result)

links = []

for i in range(0, 10):
  links.append(result['items'][i]['link'])

print(links)